name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential lcov
        
    - name: Configure project
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Debug
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate coverage
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info \
             --rc geninfo_unexecuted_blocks=1 \
             --ignore-errors mismatch
        lcov --remove coverage.info '/usr/*' '*/test/*' --output-file coverage.info
        lcov --list coverage.info || echo "Coverage generation completed with warnings"
        
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/coverage.info
