name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential lcov
        
    - name: Install Google Test and Mock (modern approach)
      run: |
        sudo apt-get install -y libgtest-dev libgmock-dev || true
        
        sudo apt-get install -y git
        git clone https://github.com/google/googletest.git -b release-1.13.0
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        cd ../..
        
    - name: Verify GMock installation
      run: |
        ls -la /usr/local/include/gmock
        ls -la /usr/local/lib/libgmock*
        ls -la /usr/include/gmock
        ls -la /usr/lib/libgmock*
        
    - name: Configure project
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Debug --parallel 2
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate coverage
      if: success()
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info --rc lcov_branch_coverage=1
        lcov --remove coverage.info \
             '*/usr/*' \
             '*/_deps/*' \
             '*/test/*' \
             '*/googletest/*' \
             '*/gmock/*' \
             --output-file coverage.info
        lcov --list coverage.info
        
    - name: Upload coverage to Coveralls
      if: success()
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/coverage.info
