name: CI Pipeline

on: [push, pull_request]

env:
  GTEST_TAG: release-1.13.0 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential lcov libgtest-dev libgmock-dev
        
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo make install
        
        cd /usr/src/gmock
        sudo cmake .
        sudo make
        sudo make install
        
    - name: Configure project
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Debug --parallel 2
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate coverage
      if: success()
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info --rc lcov_branch_coverage=1
        lcov --remove coverage.info \
             '*/usr/*' \
             '*/_deps/*' \
             '*/test/*' \
             '*/googletest/*' \
             '*/gmock/*' \
             --output-file coverage.info
        lcov --list coverage.info
        
    - name: Upload coverage to Coveralls
      if: success()
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/coverage.info
