name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake python3-pip
        pip3 install pytest pytest-cov coveralls

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

        path-to-lcov: ./coverage.xml
