name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clean build directory
      run: rm -rf build || true  # Игнорируем ошибку, если папки нет

    - name: Create build directory
      run: mkdir -p build  # -p предотвращает ошибку если папка существует

    - name: Build
      run: |
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
