name: CMake CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential lcov libgtest-dev libgmock-dev
        
    - name: Configure project
      run: |
        mkdir -p build
        cd build
        cmake -DENABLE_COVERAGE=ON ..
        
    - name: Build project
      run: |
        cd build
        cmake --build . --parallel 2
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Generate coverage
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info \
             '*/usr/*' \
             '*/_deps/*' \
             '*/test/*' \
             --output-file coverage.info
        lcov --list coverage.info

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        path-to-lcov: build/coverage.info
